### ISSUE TITLE
Validation des données

### ISSUE THREAD

**Issue by arx-it** [Geoportail-Luxembourg/qgis-pag-plugin#10]
Validation de la structure de données

**Comment by arx-it** [comment]
Lors de la sélection d’une erreur dans le module de validation, le feature est bien zoomé et sélectionné, mais la carte ne le met pas en surbrillance

**Comment by arx-it** [comment]
C'est une erreur de ma part, mes données de tests sont superposées, et donc le feature sélectionné était sous un autre. La fonction est correcte.

**Comment by jaykayone** [comment]
je n'arrive pas à tester

**Comment by jaykayone** [comment]
OK, ça fonctionne
