### ISSUE TITLE
Import GML

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#102]
When importing a GML that has been exported by the tool itself, there is an error:

Gestion;0;Geometry is empty

This sould be avoided

**Comment by arx-it** [comment]
OK je vais voir

**Comment by jaykayone** [comment]
Pourriez-vous nous fournir un fix pour ceci svp?

**Comment by arx-it** [comment]
Pouvez-vous m'envoyer le projet en question? Je viens d'en créer un vierge et j'ai créé des entités, mais je ne reproduis pas ce problème.

**Comment by jaykayone** [comment]
il faut saisir qqch dans gestion

**Comment by arx-it** [comment]
Corrigé en staging
