### ISSUE TITLE
message conernant plugin qui n'est pas présent

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#113]
![image](https://user-images.githubusercontent.com/1518019/65580043-384b3300-df79-11e9-8175-3b9e289c3e3f.png)
![image](https://user-images.githubusercontent.com/1518019/65580060-41d49b00-df79-11e9-8828-585d09445201.png)

**Comment by jaykayone** [comment]
Le GML exporté contient des tags de type nil=True

<CONST_A_CONS_POINT gml:id="CONST_A_CONS_POINT.0">
**<CATEGORIE xsi:nil="true"/>**
<NOM_FICHIER>014_PE_CONST_A_CONS</NOM_FICHIER>
<GEOMETRIE>
<gml:Point gml:id="CONST_A_CONS_POINT.geom.0" srsName="urn:ogc:def:crs:EPSG::2169">
<gml:pos>103496.8466 79178.7021995467</gml:pos>
</gml:Point>
</GEOMETRIE>
</CONST_A_CONS_POINT>

Notre checker n'accepte pas cette syntaxe.
Dans l'ancien export, ces tags étaient omis

**Comment by frankbroniewski** [comment]
Moin, is this a fresh installation? Did you enable the geometry checker plugin? Usually it comes preinstalled with QGIS, but it is not enabled by default ...

**Comment by jaykayone** [comment]
sorry, the second screenshot is not correct

<img width="987" alt="image" src="https://user-images.githubusercontent.com/1518019/65589068-c1b63180-df88-11e9-890e-d539511bc0f9.png">


I wanted to show that the plugin is actually there, but the message comes nevertheless

**Comment by frankbroniewski** [comment]
Yes, the message might be misleading. The plugin is installed, but not enabled. "you did not enable the geometry checker plugin" might be more helpful here ...

**Comment by jaykayone** [comment]
as you can see in my screenshot, it IS enabled ...

**Comment by frankbroniewski** [comment]
Really? It should be not only installed, but the checkbox needs to be ticked as well ... see my QGIS screenshot
![qgis_plugins](https://user-images.githubusercontent.com/3940114/65599847-11075c80-df9f-11e9-905a-05044ce87b93.PNG)

**Comment by jaykayone** [comment]
my bad, you are right ...

I mixed up geometry checker and topology checker

Thanks, Frank
