### ISSUE TITLE
Validierung: empty string encountered

### ISSUE THREAD

**Issue by frankbroniewski** [Geoportail-Luxembourg/qgis-pag-plugin#115]
Moin,
das vom Plugin erzeugte GML wird vom Validierer unter https://pag-upload.mi.public.lu/ nicht akzeptiert. Für den Layer NQ_PAP wird bei einem leeren COS_MIN-Wert ein leerer XML-Knoten `<COS_MIN />` erzeugt der vom Validierer mit `empty string encountered` abgewiesen wird.

Laut Règlement sind die Koeffizientenwerte fakultativ, so dass das Nicht-Vorhandensein eines Wertes keinen Fehler im Validierer aufwerfen sollte. 

Als Notlösung kann in einem Editor der Wahl mittels Suchen und Ersetzen den leeren Knoten herauslöschen, etwas das ich aber eigentlich eher vom Plugin erwarten würde (oder der Validierer würde leere Knoten aktzeptieren).

In der Attributtabelle ist das Attribut COS_MIN an den entsprechenden Stellen `NULL`.
QGIS-Version 3.14.16-Pi, OSGeo4W unter Windows 10, Plugin-Version PAG Luxembourg (QGIS3) 1.3.2

**Comment by jaykayone** [comment]
Das Problem hatten wir in einer vorherigen Version schon mal, sollte theoretisch aber behoben sein.
Könnten Sie uns eine solche Datei schicken? 
Dann können wir schauen, ob wir den Check anpassen können oder etwas am Plugin machen müssen

**Comment by frankbroniewski** [comment]
Ich habe das gerade noch einmal verifiziert, das Problem tritt mit dem o.g. System tatsächlich auf. Anbei ein Link zum Download des erzeugten GML und das QGIS-Projekt mit den Basisdaten: https://architectureetamenagement-my.sharepoint.com/:u:/g/personal/broniewski_a-a_lu/EUrj_IpiqRtMpXsDPg9TlO8BFzkYtib6CXmLqQuYBLuZWg?e=n8Ywt9

**Comment by geoportallux** [comment]
Hallo Frank, 

das Problem ist in der neuesten Version behoben.

MfG
Jef
