### ISSUE TITLE
XSD schema

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#25]
Le schéma XSD qui a été envoyé la dernière fois a été généré avec la version la plus récente de l'outil umleditor.

Il a une structure un peu différente de ce que nous avions auparavant. 
Cet XSD n'est pas utilisable dans nos outils de génération de GML et de check de GML.

Nous allons utiliser une ancienne version de l'outil pour regénérer un XSD. 
Il est possible qu'il faudra réajuster le parser...

**Comment by jaykayone** [comment]
en fait le xsd fourni la dernière fois n'était pas un schéma GML valide, c'était un schéma interlis.
désolé. je vais pousser le nouveau. c'est en plus une nouvelle version avec quelques petites modifs

**Comment by arx-it** [comment]
Dans le XSD, pour le type ZONES_SUPERPOSEESType, j'ai un attribut enfant :<xsd:element name="CATEGORIE" type="gml:CodeWithAuthorityType"/> sans restriction, auparavant c'était un énumération. Est-ce une erreur?

**Comment by jaykayone** [comment]
il s'agit d'une erreur, nous allons resoumettre une version corrigée
