### ISSUE TITLE
Ordre des couches

### ISSUE THREAD

**Issue by arx-it** [Geoportail-Luxembourg/qgis-pag-plugin#27]
![Layers ordering](https://cloud.githubusercontent.com/assets/1518019/10220925/22284bca-684b-11e5-9f97-656cbeefc279.png)

**Comment by jaykayone** [comment]
is this supposed to be part of the staging branch right now?

**Comment by arx-it** [comment]
Not yet, I have to create a configuration file to handle the layer order, but this will have to be updated while the XSD is updated. I don't have a better idea yet. Do you?

**Comment by jaykayone** [comment]
this will have to be defined in a config file with indexes per layer. Sure this will have to be update when XSD is updated, idem for the styles

**Comment by arx-it** [comment]
Done, the config file is in assets/LayerTree.json

**Comment by arx-it** [comment]
You can also rename the layers using this file
