### ISSUE TITLE
problème de schéma

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#31]
![screen shot 2015-10-26 at 08 56 44](https://cloud.githubusercontent.com/assets/1518019/10723851/834805da-7bbf-11e5-8a33-ce93546066b6.png)

Dès la création d'un projet "vide", il y a des erreurs de validation de schéma qui sont affichées

**Comment by arx-it** [comment]
Corrigé
