### ISSUE TITLE
apply styles ne fonctionne plus

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#32]
Le bouton "apply styles" n'a plus d'effet.

**Comment by arx-it** [comment]
Ca fonctionne chez moi, vérifier que les fichiers de styles correspondent bien au nouveaux nom de table du nouveau XSD. il y'a un "PAG." au début du nom de fichier.
ex : PAG.PAG.ZONE_SERV_URB -> PAG.ZONE_SERV_URB

**Comment by arx-it** [comment]
Supprimer tous les styles, et récupérer les derniers de github

**Comment by jaykayone** [comment]
OK, le problème était que la table ZAD a changé de nom, mais pas le fichier QML

**Comment by arx-it** [comment]
Corrigé en staging
