### ISSUE TITLE
Import partiel en cas d'erreur

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#37]
Lorsqu'on import un GML et qu'il y a une erreur, on se retrouve avec un import partiel.
Est-ce possible de définir une longue transaction avec un rollback en cas d'erreur?

**Comment by arx-it** [comment]
Je suis en train de les encapsuler dans une edit session

**Comment by arx-it** [comment]
CF #36

**Comment by arx-it** [comment]
Comment dois-je procéder si je détecte un erreur de données sur le GML source. Ex : une valeur non présente dans l'énumération. Je l'insère tout de même dans la couche? Et j'affiche une erreur, ou je ne l'insère pas?

**Comment by jaykayone** [comment]
Insérer la valeur, on la trouvera ensuite lors de la validation

**Comment by arx-it** [comment]
Concernant le rollback, on rollback tout l'import du GML, ou juste la couche en question?

**Comment by jaykayone** [comment]
tout le GML .. si on doit recommencer un import on ne doit pas avoir de doublons

**Comment by arx-it** [comment]
J'ai regardé, et la BD Spatialite ne supporte pas les transactions. J'ai activé les insertions dans des edit session, mais cela ne se fait que couche après couche. Impossible dans l'état actuel de faire un rollback sur tout l'import, sans faire un développement spécialisé.

**Comment by jaykayone** [comment]
dans l'état actuel, j'ai un message d'erreur qu'il y a eu un problème lors de l'import mais il n'importe pas le reste du fichier...
https://download.geoportail.lu/public.php?service=files&t=e1d645df06442ba1a5f440a3e3fa602b&download 
Je suppose que c'est un cast d'une valeur dans le champ genre qui manque 
(string selon le modèle de données, chiffre trouvé dans le fichier gml)

**Comment by arx-it** [comment]
Bug très étrange, mais ca devrait être résolu
