### ISSUE TITLE
Validation screen - allow copy & paste

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#38]
it would be nice to be able to copy and paste in the validation table.
(select all, ctrl-c) is anough usability for now

**Comment by arx-it** [comment]
Je peux autoriser la sélection de tout le tableau, mais faire un Ctr-c ne copie que la cellule en cours, et non tout le tableau.

**Comment by jaykayone** [comment]
hmm dommage, faudra évtl analyser un autre moyen genre export csv ... nous allons analyser celà et proposer un change request

**Comment by jaykayone** [comment]
offrir une fonction d'export CSV avec coordonnées XY du centroïde

**Comment by jaykayone** [comment]
Tested: +1
