### ISSUE TITLE
Supporter une session de transaction pour un import

### ISSUE THREAD

**Issue by arx-it** [Geoportail-Luxembourg/qgis-pag-plugin#39]
Une idée serait d'ajouter un attribut "ImportID" à toutes les tables, ce qui permettrait d'identifier et de supprimer toutes les entités d'un import en cas de problème.
- [ ] L’export GML sera modifié pour exclure le champ « ID Import ».

**Comment by geoportallux** [comment]
Bonne idée

**Comment by jaykayone** [comment]
Bonus: Montrer une liste d'imports dans un projet que l'utilisateur peut choisir d'annuler

**Comment by jaykayone** [comment]
Please add a financial quote for the delete function per import session

**Comment by jaykayone** [comment]
super !!
