### ISSUE TITLE
Import GML

### ISSUE THREAD

**Issue by arx-it** [Geoportail-Luxembourg/qgis-pag-plugin#4]
Import d'un fichier GML conforme au schema XSD

**Comment by jaykayone** [comment]
![screen shot 2015-10-26 at 09 20 15](https://cloud.githubusercontent.com/assets/1518019/10724201/cb3d4fdc-7bc2-11e5-8fda-f6ed08042d92.png)
ne fonctionne pas

**Comment by jaykayone** [comment]
screenshot updated

here is the stacktrace:
Traceback (most recent call last):
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_data.py", line 60, in run
    importer[extension](selected_file[0])
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_data.py", line 94, in importGml
    self._importGmlLayer(gmllayer, xsdtype)
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_data.py", line 115, in _importGmlLayer
    gml_xsd_fieldindexmap = self._getFieldMap(gml_layer, project_layer)
NameError: global name 'project_layer' is not defined

**Comment by arx-it** [comment]
Corrigé en staging

**Comment by jaykayone** [comment]
fonctionne super bien!

Par contre, j'ai un fichier qui génère cette erreur:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_data.py", line 60, in run
    importer[extension](selected_file[0])
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_data.py", line 98, in importGml
    self._importGmlLayer(gmllayer, xsdtype)
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_data.py", line 128, in _importGmlLayer
    feature.setGeometry(gmlfeature.geometry())
TypeError: QgsFeature.setGeometry(QgsGeometry): argument 1 has unexpected type 'NoneType'

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.3-Wien Wien, 313a6bc

Python path: ['C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python', u'C:/Users/ity425/.qgis2/python', u'C:/Users/ity425/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python/plugins', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\bin\python27.zip', 'C:\PROGRA~1\QGISWI~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISWI~1\bin', 'C:\PROGRA~1\QGISWI~1\apps\Python27', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', u'C:/Users/ity425/.qgis2//python', 'C:\PROGRA~1\QGISWI~1\apps\qgis-ltr\python\plugins\fTools\tools', 'C:/temp/test_new']

**Comment by jaykayone** [comment]
https://download.geoportail.lu/public.php?service=files&t=3ede8cc3d08a113c7ad2b1f0002c612f&download
