### ISSUE TITLE
documents récents

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#42]
pour une raison X, les projets créés et sauvegardés avec le plugin ne figurent pas dans le "documents récents".
Est-ce que ceci peut être changé?

**Comment by arx-it** [comment]
Je ne constate pas ce problème de mon côté, les projets sont bien présents dans la liste des  projets récents.

**Comment by jaykayone** [comment]
Chez moi c'est quand même systématique, sur 3 machines différentes.

Je crée mes projets avec l'outil PAG dans /tmp (ou c:\temp), travaille
dedans, sauvegarde, ferme, rouvre et le projet n'est pas dans les projets
récents :(

On Tue, Nov 10, 2015 at 11:38 AM, arx-it notifications@github.com wrote:

> Je ne constate pas ce problème de mon côté, les projets sont bien présents
> dans la liste des projets récents.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Geoportail-Luxembourg/qgis-pag-plugin/issues/42#issuecomment-155384553
> .

## 

Jeff Konnen

**Comment by arx-it** [comment]
Ok, je comprends, ce doit être parce que le plugin ne passe pas par la boite de dialogue Save as. Effectivement mes projets sont là car je les ai ouverts. Je vais voir ce qu'il est possible de faire.

**Comment by arx-it** [comment]
QGIS ne le fait qu'en cas de nouveau fichier, avec boite de save as.
Il n'y a pas de fonction python pour y accéder.
D'après le code source, à partir de QGIS 2.12, il sera possible d'ajouter un fichier récent par le code.

**Comment by jaykayone** [comment]
Tested: +1
