### ISSUE TITLE
Topology tools

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#44]
The topology tools do not allow any tolerance. There are often minimal overlaps that are found and that cannot be easily fixed.

Could you analyze what are the possibilities to either:
- Check topology with a certain tolerance (eg 1cm)
- Clean topology (eg the use of v.clean of grassgis ?) in a tolerance of eg 1cm

**Comment by jaykayone** [comment]
autres possibilités évoquées: arrondi à l'import ? snapping ?

**Comment by arx-it** [comment]
Utilisation de l'outil GRASS v.clean.advanced : https://grass.osgeo.org/grass64/manuals/v.clean.html
Pour l'instant l'outil, supprime les petites surfaces < 0.1 m2 de la couche sélectionnée => plus d'erreur avec le topology checker "no overlaps"
L'outil n'est pas lancé automatiquement en fin d'import, car les erreurs topo sont déjà présentes dans le fichier d'origine, l'import n'y est donc pour rien.
Il faut tester l'outil en l'état, je me garde du temps pour des modifs selon les résultats.

**Comment by jaykayone** [comment]
c'est un bon début
