### ISSUE TITLE
Import SHP

### ISSUE THREAD

**Issue by arx-it** [Geoportail-Luxembourg/qgis-pag-plugin#5]
Import d'un fichier SHP

**Comment by arx-it** [comment]
Import SHP poussé en staging.
Pas de sauvegarde/chargement de la configuration pour l'instant.

**Comment by jaykayone** [comment]
Après un premier import de shape avec succès, j'ai ceci comme message d'erreur lorsque je veux importer un deuxième shape
![screen shot 2015-11-05 at 15 27 38](https://cloud.githubusercontent.com/assets/1518019/10970925/d38b221a-83d1-11e5-8de6-1fa352fa4545.png)

**Comment by jaykayone** [comment]
en fait c'est parce que j'avais intégré un WMS comme couche de fond

**Comment by arx-it** [comment]
Ok, je vois

**Comment by arx-it** [comment]
Ok, j'ai exclu les couches raster, j'ai également poussé la gestion de la configuration (chargement et sauvegarde)
