### ISSUE TITLE
mise en place repository pour distribution plugin 

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#50]
repository hosté par le géoportail

**Comment by arx-it** [comment]
Avez-vous déjà un url pour que je puisse configurer le fichier xml?

**Comment by jaykayone** [comment]
On peut retenir https://pag-upload.mi.public.lu/qgis-repository.xml

**Comment by jaykayone** [comment]
Ca me gêne de modifier un fichier PY.
Ne pourrait on pas mettre le numéro de version dans un fichier de config?

**Comment by arx-it** [comment]
Dans l'absolu il ne sert à rien en fait. A l'origine c'était pour contrôler le projet et le mettre éventuellement à jour. Mais en réalité ce contrôle se fait systématiquement quelle que soit la version.

**Comment by jaykayone** [comment]
OK, enlevez-le alors du code et de la doc admin, ce sera plus cohérent

**Comment by arx-it** [comment]
Fixed

**Comment by arx-it** [comment]
Il faut créer un nouveau projet, les anciens ne seront plus reconnus comme projet pag.
