### ISSUE TITLE
Import Allow the configuration window to be resized

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#51]
the window can be resized but the grid does not adapt
![snipimage 2](https://cloud.githubusercontent.com/assets/1518019/11141399/4b293d2a-89e5-11e5-8a12-ca6d4ff7961c.JPG)

**Comment by arx-it** [comment]
Window does not currently allow dynamic resizing. both SHP and dxf window have been resized.
