### ISSUE TITLE
Import config: File picker

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#54]
Add file picker like in the edit tool
![snipimage 2 2](https://cloud.githubusercontent.com/assets/1518019/11141476/212dd296-89e6-11e5-9502-3f3d6ec1ca0b.JPG)

**Comment by arx-it** [comment]
The custom editor file picker will be used.

**Comment by jaykayone** [comment]
TESTED: +1
