### ISSUE TITLE
Filenames

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#55]
We should only save the filename, not the entire path
![screen shot 2015-11-13 at 09 38 02](https://cloud.githubusercontent.com/assets/1518019/11141974/53a7c886-89ea-11e5-8c89-d032c21cdadb.png)

**Comment by jaykayone** [comment]
even without the extension !

**Comment by arx-it** [comment]
This is not configurable with the Filename editor widget.
A custom editor widget has to be developped for this purpose.

**Comment by jaykayone** [comment]
Ok please add it to the enhancement quotes

**Comment by jaykayone** [comment]
Tested: +1
