### ISSUE TITLE
Import - Field types

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#56]
the field types in import dialog are not identical to the ones in the editor.

in this case cos/cus should allow 2 decimals instead of 1 
![snipimage 2 3](https://cloud.githubusercontent.com/assets/1518019/11141997/796cfc4e-89ea-11e5-9adc-418b0871be94.JPG)

**Comment by arx-it** [comment]
The XSD Schema indicates there should be 1 decimal : min 0.0 max 1.0.
In the field editor I can only specify the step (here 0,10), but not the decimals to display.
But in the import I can set the decimals.
It seems, the field editor is fixed to 2 decimals.

**Comment by jaykayone** [comment]
TESTED: +1
