### ISSUE TITLE
feature editing - auto open form

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#57]
Can you set the settings that qgis automatically opens the edit form when clicking on a feature ?
![screen shot 2015-11-13 at 09 45 13](https://cloud.githubusercontent.com/assets/1518019/11142109/432f69e0-89eb-11e5-8f80-545e6f346e53.png)

(Setting "auto open form" in the bottom right of the image

**Comment by arx-it** [comment]
Done
