### ISSUE TITLE
Import DXF

### ISSUE THREAD

**Issue by arx-it** [Geoportail-Luxembourg/qgis-pag-plugin#6]
Import d'un fichier DXF avec mapping

**Comment by arx-it** [comment]
Comment mapper les géométries DXF vers Spatialite?
Proposition :
POINT => POINT
LINE, POLYLINE, LWPOLYLINE => Polyline
HATCH => Polygon

**Comment by jaykayone** [comment]
le problème est en effet connu. Les polygones sont des fois des hatches des fois des polylines fermés.

Je propose que si on mappe un calque dwg vers une table de type polygon, on essaye de convertir l'entrant en polygone?

**Comment by arx-it** [comment]
Donc je teste si la polyligne est fermée, et je la convertis en polygone.

**Comment by arx-it** [comment]
Mais une polyligne fermée vers une couche polyligne, passera.

**Comment by jaykayone** [comment]
oui, je pense que c'est la meilleure approche

**Comment by arx-it** [comment]
Fonction en staging

**Comment by jaykayone** [comment]
```
Traceback (most recent call last):
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_data.py", line 65, in run
    self.importer.runImport()
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf.py", line 33, in runImport
    self.dlg = ImportDxfDialog(self.filename)
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 68, in __init__
    self._loadLayersMapping()
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 178, in _loadLayersMapping
    layer_mapping = self._getLayerMappingFromSourceDxfLayer(dxf_layername)
  File "C:/Users/ity425/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 158, in _getLayerMappingFromSourceDxfLayer
    layer_mapping.setSourceLayerFilter('Layer=\'{}\''.format(dxf_layername))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)
```

**Comment by arx-it** [comment]
C'est corrigé, le nom du calque avait un caractère spécial : ART 17 FLÃCHEN_SURFACE

**Comment by jaykayone** [comment]
un "disable all" serait pratique si on ne veut importer qu'un calque.
je viens de passer 5 minuter à désélectionner des coches

**Comment by jaykayone** [comment]
j'ai essayé d'importer la couche "Zone d'habitation" du DXF en question, mais rien n'a été importé ?

**Comment by arx-it** [comment]
Quel est le nom exact de la couche? et vers quelle couche QGIS?

**Comment by jaykayone** [comment]
j'enverrai le json cet apm

**Comment by arx-it** [comment]
OK, je pense que c'est parce que le calque DXF contient une apostrophe. C'est corrigé

**Comment by arx-it** [comment]
Pour les coches, en attendant : editer le fichier PagLuxembourg\widgets\import_data\importer.py
Ligne 337, mettre self.setEnabled(False)
Ne fonctionne pas au chargement d'une config, just pour un nouvel import

**Comment by jaykayone** [comment]
je m'en doutais (pour l'apostrophe)

**Comment by arx-it** [comment]
Oui c'est un peu l'erreur classique en SQL...
