### ISSUE TITLE
TABLE GESTION

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#60]
La table gestion n'est plus dans la base ni dans le projet.
Je n'ai pas réussi à la rajouter grâce aux LayerTree.json

**Comment by jaykayone** [comment]
pardon, elle est bien dans la base, mais pas dans le projet

**Comment by arx-it** [comment]
Elle manquait au JSON effectivement, par contre en le modifiant cela fonctionne :
{
      "Name": "Gestion",
      "IsGroup": false,
      "TableName": "GESTION.Gestion",
      "Nodes": []
    }

**Comment by arx-it** [comment]
C'est en staging avec les 2 PR
