### ISSUE TITLE
editer valeur depuis liste d'erreurs

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#62]
si je trouve une erreur et que je doubleclique sur l'enregistrement, le masque s'ouvre.
si je choisis une nouvelle valeur et clique OK, le programme fait une erreur et ensuite il se casse..
![screen shot 2015-11-25 at 17 22 07](https://cloud.githubusercontent.com/assets/1518019/11402635/2a57b4e2-9399-11e5-9f89-3fe640771463.png)
![screen shot 2015-11-25 at 17 22 15](https://cloud.githubusercontent.com/assets/1518019/11402636/2c168e48-9399-11e5-9304-d1ab69af09c4.png)
![screen shot 2015-11-25 at 17 22 22](https://cloud.githubusercontent.com/assets/1518019/11402638/2e225af0-9399-11e5-94b5-2b3d654c9d21.png)
![screen shot 2015-11-25 at 17 22 29](https://cloud.githubusercontent.com/assets/1518019/11402641/2ff99b54-9399-11e5-844e-c0d070563d0d.png)

**Comment by arx-it** [comment]
Avez-vous le détail du bouton Show Details?

**Comment by jaykayone** [comment]
malheureusement pas, si je réessaie maintenant, le message ne vient même plus

**Comment by arx-it** [comment]
Semble être corrigé, maintenant

**Comment by jaykayone** [comment]
+1
