### ISSUE TITLE
Clean topology  -- suite

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#71]
avec ce fichier https://download.geoportail.lu/public.php?service=files&t=43391272ea0cfd0309156e1ce570bd84&download le clean topology a pu éliminer 160 de 210 erreurs topologiques
Est-ce qu'on peut aussi trouver une solution pour faire un clean des gaps minimaux?

**Comment by arx-it** [comment]
v.clean supprime aussi les gaps, il faut jouer avec la tolérance, je peux faire une boite de dialogue qui permet de l'ajuster

**Comment by arx-it** [comment]
J'ai fait une boite de dialogue pour l'outil, cela permet d'ajuster la tolérance et de supprimer les petits gaps
