### ISSUE TITLE
clean topology - efface des éléments

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#72]
avec ce fichier: 
https://download.geoportail.lu/public.php?service=files&t=43391272ea0cfd0309156e1ce570bd84&download

Ca m'est arrivé 2 fois que le clean topology ait effacé des éléments.
Probablement lorsqu'il y a une sélection avant de cliquer sur clean

**Comment by arx-it** [comment]
Je vais vérifier

**Comment by arx-it** [comment]
Corrigé
