### ISSUE TITLE
problème lors de l'import

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#76]
Une erreur est apparue lors de l'exécution du code Python :
AttributeError: 'QgsPolygonV2' object has no attribute 'validateGeometry'

Traceback (most recent call last):
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 439, in _launchImport
    self._importLayer(self.dxflayer_linestrings, qgis_layer, layer_indexmapping, progress2)
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\importer.py", line 205, in _importLayer
    if not self._validateGeometry(mapping.sourceLayerName(), src_polygon):
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\importer.py", line 260, in _validateGeometry
    errors = feature.geometry().validateGeometry()
AttributeError: 'QgsPolygonV2' object has no attribute 'validateGeometry'

Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Version de QGIS : 2.12.1-Lyon Lyon, 16760fd
Chemin Python :

·                     C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins\processing
·                     C:/PROGRA~1/QGISLY~1/apps/qgis/./python
·                     C:/Users/RCF337/.qgis2/python
·                     C:/Users/RCF337/.qgis2/python/plugins
·                     C:/PROGRA~1/QGISLY~1/apps/qgis/./python/plugins
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
·                     C:\PROGRA~1\QGISLY~1\bin\python27.zip
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\DLLs
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\plat-win
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\lib-tk
·                     C:\PROGRA~1\QGISLY~1\bin
·                     C:\PROGRA~1\QGISLY~1\apps\Python27
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\PIL
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\win32
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\win32\lib
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\Pythonwin
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
·                     C:\PROGRA~1\QGISLY~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
·                     C:/Users/RCF337/.qgis2//python
·                     C:\PROGRA~1\QGISLY~1\apps\qgis\python\plugins\fTools\tools
Y:/David/Test_formation_INAP/dwgOlm

**Comment by arx-it** [comment]
Est-ce possible d'avoir le fichier et le mapping correspondant? Vous pouvez éventuellement les déposer ici : https://www.dropbox.com/request/xSj7IadDGM3GOUI6AIDp

**Comment by arx-it** [comment]
Corrigé en Staging
