### ISSUE TITLE
packaging du plugin

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#78]
est-ce que vous pouvez me rappeler comment packager le plugin de manière à ce que je puisse publier une version sur notre site?

**Comment by arx-it** [comment]
Il y'a un paragraphe sur sur la publication dans la doc d'admin (admin/doc/index.html)

**Comment by jaykayone** [comment]
OK, ça fonctionne: https://pag-upload.mi.public.lu/qgis-repository.xml
