### ISSUE TITLE
Validation topologiques

### ISSUE THREAD

**Issue by arx-it** [Geoportail-Luxembourg/qgis-pag-plugin#8]
Configuration de l'outil de validation topologique avec les règles définies

**Comment by jaykayone** [comment]
Est-ce qu'on peut

1) faire en sorte que le plugin de validation topologique soit activé lors qu'on active PAGLuxembourg
2) Mettre un bouton dans la toolbar pour ouvrir la fenêtre?

**Comment by arx-it** [comment]
Je viens de constater un comportement du topology checker : Il dépend de la langue. Il ne faut pas créer un projet avec QGIS en Anglais et l'ouvrir ensuite en français, sinon les règles ne sont pas reconnues.

**Comment by jaykayone** [comment]
OK... de toute façon nous avons quelques soucis avec ce module, que nous voulons analyser en détail et voir si nous voulons introduire un change request pour cette problématique
