### ISSUE TITLE
auto open form

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#80]
je viens d'installer le plugin from scratch dans un nouvelle install de qgis depuis le repository officel et le "auto open form" n'était pas coché

**Comment by arx-it** [comment]
Le setting est disponible à deux endroits, est-ce que la form s'affiche quand même ou non?

**Comment by jaykayone** [comment]
non, seulement après avoir coché la case

**Comment by arx-it** [comment]
C'est réactivé.
Il y'a un auto open form lors de la création d'un objet, et un auto open form sur le Identify.
En staging
