### ISSUE TITLE
fusion de géométries

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#81]
ceci est probablement un bug dans qgis mais ça nous gêne dans notre processus:

Lorsque je sélectionne deux features dans la carte et que les fusionne avec l'outil "merge features" de la barre d'édition avancée, les features disparaissent ..

Y a-t-il peut être un workaround à mettre dans le plugin pour que ça marche quand même?

**Comment by arx-it** [comment]
Effectivement c'est surprenant.
Sinon le Geoprocessing "Delete duplicate geometries" fonctionne bien. Je ne sais pas si cela correspond au besoin.

**Comment by jaykayone** [comment]
en fait ce que j'essaie de faire est le workflow suivant:
- utilser le clean -> il fait une intersection (par exemple HAB_1 avec AGR)
- détecter les nouveaux doublons avec le topology checker
- effacer un des deux (AGR dans la plupart des cas)

jusque là ça fonctionne

comme dernière étape je voudrais fusionner la mini surface qui a été découpée et gardée avec son voisin (HAB_1 avec HAB_1) -> C'est là que ça foire et que je n'ai actuellement pas de solution.

Le géoprocessing "delete duplicate geometries" ne me laisse pas choisir laquelle je veux garder... et il ne fait quand même pas la fusion des autres

**Comment by arx-it** [comment]
De mon côté, lorsque je fais un clean, je n'ai pas de mini surface, les polygones adjacents ne se chevauchent plus. Avez-vous un cas de figure ou je peux constater la création de cette mini surface?

**Comment by geoportallux** [comment]
C'est en mettant une tol�rance de 1m

**Comment by jaykayone** [comment]
voici une vidéo qui illustre les différents soucis:
- intersection créées au lieu de cleaning
- dissolve qui ne marche pas

https://www.youtube.com/watch?v=ZK2UQf0I0MI

Ce serait très important pour nous d'avoir une solution qui marche à ce niveau pour notre cours de mercredi prochain. A l'heure actuelle un cleaning n'est pas vraiment possible

**Comment by jaykayone** [comment]
juste pour clarifier:
- le fait que l'outil de clean fasse des intersections n'est pas idéal. Ce serait meilleur s'il faisait un clean au lieu de faire des intersections qu'on doit alors aller merger manuellement

**Comment by arx-it** [comment]
Essayez de tester l'enchainement suivant (dans la toolbox processing) :
- v.clean > outil rmarea > threshold 1
- delete duplicate geometries sur la nouvelle couche
- dissolve sur la nouvelle couche > décocher "dissolve all" > choisir le champ OGC_FID pour fusionner

J'ai mis un model ici : https://www.dropbox.com/s/572ph0o9krtbhq0/CleanModel.model?dl=0

**Comment by geoportallux** [comment]
Bonjour,

nous venons de tester.

ça donne en effet le résultat souhaité à un souci près:

Le treshold n'est pas respecté. 
Même des superpositions de plusieurs centaines de m2 sont éliminées et fusionnées automagiquement sans qu'on puisse choisir si on veut garder HAB ou FOR. 

Dans la tolérance c'est pas grave, le choix de la zone à garder peut être "au hasard", 
mais pour les grandes superpositions ça ne peut pas se vaire automatiquement

**Comment by arx-it** [comment]
Dans ce cas, ne pas faire de delete duplicate geometries au milieu : https://www.dropbox.com/s/yn25wy3dfkd11iy/CleanModel_v2.model?dl=0

**Comment by arx-it** [comment]
Du coup les grandes superpositions vont à nouveau sortir comme erreur topologique, il faudra les corriger manuellement

**Comment by geoportallux** [comment]
je confirme que ça amène au résultat souhaîté.

pouvez vous inclure ce workflow dans votre outil clean?

**Comment by arx-it** [comment]
Voilà, j'ai intégré à Staging
