### ISSUE TITLE
Régression: problème de topologie !!

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#83]
nous venons de nous rendre compte d'une grande régression.

depuis que vous faites un simplify de toutes les géométries nous créons beaucoup de problèmes topologiques.

Est-ce que vous pouvez simplifier que les features qui ne passent pas le isvalid?

https://github.com/Geoportail-Luxembourg/qgis-pag-plugin/blob/staging/widgets/import_data/importer.py#L264

Je vais vous envoyer un fichier qui est clean selon nos tests et qui après import avec la dernière version présente des erreurs tologiques ce qui ne devrait pas être le cas!

**Comment by arx-it** [comment]
Je vais regarder ce point demain matin, et également une éventuelle solution pour le merge.

**Comment by arx-it** [comment]
Ok, j'ai mis la tolérance à 0, pas à 1mm.

**Comment by jaykayone** [comment]
Super, merci
