### ISSUE TITLE
dissolve qui ne marche pas

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#85]
Le dissolve qui ne fonctionne pas est assez gênant.
Est-ce que vous pourriez le remonter chez QGIS ?

**Comment by arx-it** [comment]
J'ai fait des tests pour isoler le bug, et j'ai remarqué que cela vient du fait que le champ ImportId est caché.
Si on affiche le champ ImportId, en lui mettant un éditeur de type texte, la fusion fonctionne.
Je vais remonter le bug quoi qu'il en soit, car il se reproduit en dehors d'un projet PAG.

**Comment by jaykayone** [comment]
Cool, au court terme on pourrait alors montrer le champ

**Comment by arx-it** [comment]
Bug filed : https://hub.qgis.org/issues/14235

**Comment by arx-it** [comment]
J'ai temporairement affiché le champ ImportId dans le code.
J'en ai profité pour poussé le tut dans la branche master.

**Comment by geoportallux** [comment]
super !
ça marche

**Comment by arx-it** [comment]
Le bug a été corrigé dans la version master de QGIS, il devrait être corrigé dans la prochaine version de QGIS.
