### ISSUE TITLE
problème repository

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#87]
notre repository fonctionne bien sur mac mais pas sur tous les pcs:

https://pag-upload.mi.public.lu/qgis-repository.xml?qgis=2.12

Même si le dépôt devient vert dans la liste des dépôts, le plugin n'est pas proposé.
Sur certaines machines ça marche, sur certaines, ça ne marche pas ..

Une idée?

**Comment by arx-it** [comment]
La version de QGIS est elle bien toujours >2.12.1?

**Comment by jaykayone** [comment]
oui, 2.12.2 et 2.12.3
est-ce que ça marche chez vous par exemple?

je viens de tester sur un laptop et sur l'infrastructure de formation et sur les deux ça ne marche pas

**Comment by arx-it** [comment]
Je vais l'installer sur une autre machine et je vais voir

**Comment by arx-it** [comment]
Comportement assez étrange.
A priori en mettant cette ligne dans le XML : <pre>&lt;qgis_maximum_version>2.99.0&lt;/qgis_maximum_version></pre>
Il faut ensuite éditer le dépot dans QGIS, le désactiver, puis le réactiver.
Ca fonctionne chez moi.

**Comment by arx-it** [comment]
Commentaire précédent mis à jour

**Comment by jaykayone** [comment]
OK je vais essayer quand j'aurai accès en écriture au repository

**Comment by jaykayone** [comment]
bien vu, en fait min et max étaient identiques et ça marche sur mac vu que la version mac est 2.12.1 et que sur windows on a 2.12.2 ou 2.12.3 ...
