### ISSUE TITLE
problème sur mac

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#88]
un client a toujours ce souci sur son mac.
je ne l'ai pas chez moi par contre
![fehlermeldung](https://cloud.githubusercontent.com/assets/1518019/13104294/83c82890-d55c-11e5-9987-314e466129c4.png)

**Comment by arx-it** [comment]
Demandez lui de mettre QGIS en Anglais et de retester.

**Comment by geoportallux** [comment]
oui ça aide

**Comment by arx-it** [comment]
Les règles topologiques sont identifiées par leur noms dans la langue de QGIS (et non un identifiant universel).
Le plugin a été testé en Anglais et Français, et non Allemand.
