### ISSUE TITLE
Problem with compatibility of json files

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#95]
```
2016-05-27T10:01:29 1 Traceback (most recent call last):
File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 429, in _launchImport
layer_indexmapping = layer_mapping.asIndexFieldMappings(qgis_layer.dataProvider().fields())
File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\importer.py", line 712, in asIndexFieldMappings
for source, destination, constant_value, enabled, value_map in self.fieldMappings():
ValueError: need more than 4 values to unpack
```

**Comment by jaykayone** [comment]
it is a json file from the previous version, it does not work in the new version

**Comment by dhottua** [comment]
Also den jason mapped se richteg. Beim import scheisst en weg kritt nix ran

**Comment by jaykayone** [comment]
it is correctly mapped, but it does not work when importing

**Comment by arx-it** [comment]
Please provide the json, because the json format has not been changed since the first release of the plugin.

**Comment by arx-it** [comment]
J'ai testé, comme annoncé, le format de configuration JSON du mapping n'a pas changé depuis la première mise en production, je ne vais donc pas effectuer de modification.
En revanche, j'ai modifié votre fichier : https://www.dropbox.com/s/0io7f2fpr9xftts/document.json?dl=0
La modification a apporter est de rajouter les[] à la fin d'une section FieldMapping, exemple après le true :

<pre><code>
"FieldMapping": [
      [
        null,
        "CODE",
        null,
        true,
        []
      ],
</code></pre>

**Comment by jaykayone** [comment]
ce fichier a par contre été généré avec l'outil.
y aurait-il un bug à cet endroit là?

**Comment by arx-it** [comment]
Comme discuté au téléphone, ce fichier provient d'une version pré-release du plugin, les utilisateurs utilisant la première release n'ont donc pas ce problème.
