### ISSUE TITLE
problem when cleaning topo

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#96]
```
2016-05-27T10:28:41 1 Traceback (most recent call last):
File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean_dialog.py", line 53, in _launchCleaning
self.topoclean.cleanLayer(self.layer, self.sbThreshold.value())
File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean.py", line 69, in cleanLayer
vclean_layer = QgsVectorLayer(result['output'], 'VClean', 'ogr')
TypeError: 'NoneType' object has no attribute '__getitem__'
2016-05-27T10:29:01 1 Traceback (most recent call last):
File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean_dialog.py", line 53, in _launchCleaning
self.topoclean.cleanLayer(self.layer, self.sbThreshold.value())
File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean.py", line 69, in cleanLayer
vclean_layer = QgsVectorLayer(result['output'], 'VClean', 'ogr')
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by arx-it** [comment]
Pouvez-vous fournir le projet en question? Avec le moyen de reproduire? Car de mon côté j'y arrive.
QGIS V2.14.2

**Comment by dhottua** [comment]
Voilâ. J’ai effectué un contrôle topo et après un nettoyage 50m !

Meilleurs Salutations,

David HOTTUA

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère de l’Intérieur

19, rue Beaumont . L-1219 Luxembourg
Tél. (+352) 247-84634

E-mail : david.hottua@mi.etat.lumailto:david.hottua@mi.etat.lu
www.gouvernement.luhttp://www.gouvernement.lu/ . www.luxembourg.luhttp://www.luxembourg.lu/

**Comment by arx-it** [comment]
Bonjour,
J'ai trouvé un problème lorsque la couche ne contient pas de feature. J'ai corrigé en Staging, pouvez-vous vérifier que le problème venait de là?

**Comment by dhottua** [comment]
Bonour,

Il y a tjr des erreurs en exécutant le nettoyage

Une erreur est survenue lors de l'éxécution du code Python:
TypeError: 'NoneType' object has no attribute '**getitem**'
Traceback (most recent call last):
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean_dialog.py", line 53, in _launchCleaning
    self.topoclean.cleanLayer(self.layer, self.sbThreshold.value())
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean.py", line 74, in cleanLayer
    vclean_layer = QgsVectorLayer(result['output'], 'VClean', 'ogr')
TypeError: 'NoneType' object has no attribute '__getitem__'

Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
Version de QGIS : 2.14.3-Essen Essen, cf2ebb8
Chemin Python :
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\processing
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python
·                     C:/Users/RCF337/.qgis2/python
·                     C:/Users/RCF337/.qgis2/python/plugins
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\bin\python27.zip
·                     C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
·                     C:\PROGRA~1\QGISES~1\bin
·                     C:\PROGRA~1\QGISES~1\apps\Python27
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
·                     C:/Users/RCF337/.qgis2//python
·                     C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:/Users/RCF337/Desktop/test/test1

**Comment by dhottua** [comment]
Bonjour,

Je transmets à mon collègue qui s’est occupés des derniers développements, je serai de retour au bureau vendredi.

Cordialement,

Matthieu BACH
Chef de projet, Expert

[cid:image001.jpg@01D0E0D3.58A3B770]

mba@arxit.commailto:mba@arxit.com
www.arxit.comhttp://www.arxit.com/

Genève
45 Av. de la Praille
1227 Carouge Genève
022 344 45 10

Lyon
20A Bd Eugène Deruelle
69432  Lyon cedex 03
+33 (0)4 78 03 10 08

Paris
183-189 Av. de Choisy
75013 Paris
+33 (0)1 78 09 94 37

De : David Hottua <David.Hottua@mi.etat.lu<mailto:David.Hottua@mi.etat.lu>>
Date : mardi, 31 mai 2016 11:16
À : Geoportail-Luxembourg/qgis-pag-plugin <reply@reply.github.com<mailto:reply@reply.github.com>>, Geoportail-Luxembourg/qgis-pag-plugin <qgis-pag-plugin@noreply.github.com<mailto:qgis-pag-plugin@noreply.github.com>>
Cc : Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>, Matthieu Bach <mba@arxit.com<mailto:mba@arxit.com>>, Jeff Konnen <jeff.konnen@act.etat.lu<mailto:jeff.konnen@act.etat.lu>>
Objet : RE: [Geoportail-Luxembourg/qgis-pag-plugin] problem when cleaning topo (#96)

Bonour,

Il y a tjr des erreurs en exécutant le nettoyage

Une erreur est survenue lors de l'éxécution du code Python:
TypeError: 'NoneType' object has no attribute '**getitem**'
Traceback (most recent call last):
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean_dialog.py", line 53, in _launchCleaning
    self.topoclean.cleanLayer(self.layer, self.sbThreshold.value())
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean.py", line 74, in cleanLayer
    vclean_layer = QgsVectorLayer(result['output'], 'VClean', 'ogr')
TypeError: 'NoneType' object has no attribute '__getitem__'

Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
Version de QGIS : 2.14.3-Essen Essen, cf2ebb8
Chemin Python :
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\processing
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python
·                     C:/Users/RCF337/.qgis2/python
·                     C:/Users/RCF337/.qgis2/python/plugins
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\bin\python27.zip
·                     C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
·                     C:\PROGRA~1\QGISES~1\bin
·                     C:\PROGRA~1\QGISES~1\apps\Python27
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
·                     C:/Users/RCF337/.qgis2//python
·                     C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:/Users/RCF337/Desktop/test/test1

**Comment by jaykayone** [comment]
```
Une erreur est survenue lors de l'éxécution du code Python:
TypeError: 'NoneType' object has no attribute '__getitem__'

Traceback (most recent call last):
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean_dialog.py", line 53, in _launchCleaning
    self.topoclean.cleanLayer(self.layer, self.sbThreshold.value())
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean.py", line 91, in cleanLayer
    clean_layer = QgsVectorLayer(result['OUTPUT'], 'Clean', 'ogr')
TypeError: 'NoneType' object has no attribute '__getitem__'


Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Version de QGIS : 2.14.3-Essen Essen, cf2ebb8
Chemin Python :

·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\processing
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python
·                     C:/Users/RCF337/.qgis2/python
·                     C:/Users/RCF337/.qgis2/python/plugins
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\bin\python27.zip
·                     C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
·                     C:\PROGRA~1\QGISES~1\bin
·                     C:\PROGRA~1\QGISES~1\apps\Python27
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
·                     C:/Users/RCF337/.qgis2//python
·                     C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:/Users/RCF337/Desktop/test0950
```

**Comment by arx-it** [comment]
Bonjour,

Je transmets à mon collègue,

Cordialement,

Matthieu BACH
Chef de projet, Expert

[cid:image001.jpg@01D0E0D3.58A3B770]

mba@arxit.commailto:mba@arxit.com
www.arxit.comhttp://www.arxit.com/

Genève
45 Av. de la Praille
1227 Carouge Genève
022 344 45 10

Lyon
20A Bd Eugène Deruelle
69432  Lyon cedex 03
+33 (0)4 78 03 10 08

Paris
183-189 Av. de Choisy
75013 Paris
+33 (0)1 78 09 94 37

De : Jeff Konnen <notifications@github.com<mailto:notifications@github.com>>
Répondre à : Geoportail-Luxembourg/qgis-pag-plugin <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mardi, 7 juin 2016 10:55
À : Geoportail-Luxembourg/qgis-pag-plugin <qgis-pag-plugin@noreply.github.com<mailto:qgis-pag-plugin@noreply.github.com>>
Cc : Matthieu Bach <mba@arxit.com<mailto:mba@arxit.com>>, Assign <assign@noreply.github.com<mailto:assign@noreply.github.com>>
Objet : Re: [Geoportail-Luxembourg/qgis-pag-plugin] problem when cleaning topo (#96)

Une erreur est survenue lors de l'éxécution du code Python:
TypeError: 'NoneType' object has no attribute '**getitem**'

Traceback (most recent call last):
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean_dialog.py", line 53, in _launchCleaning
    self.topoclean.cleanLayer(self.layer, self.sbThreshold.value())
  File "C:/Users/RCF337/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean.py", line 91, in cleanLayer
    clean_layer = QgsVectorLayer(result['OUTPUT'], 'Clean', 'ogr')
TypeError: 'NoneType' object has no attribute '__getitem__'

Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
Version de QGIS : 2.14.3-Essen Essen, cf2ebb8
Chemin Python :

·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins\processing
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python
·                     C:/Users/RCF337/.qgis2/python
·                     C:/Users/RCF337/.qgis2/python/plugins
·                     C:/PROGRA~1/QGISES~1/apps/qgis/./python/plugins
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\bin\python27.zip
·                     C:\PROGRA~1\QGISES~1\apps\Python27\DLLs
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\plat-win
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\lib-tk
·                     C:\PROGRA~1\QGISES~1\bin
·                     C:\PROGRA~1\QGISES~1\apps\Python27
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\win32\lib
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Pythonwin
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
·                     C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
·                     C:/Users/RCF337/.qgis2//python
·                     C:\PROGRA~1\QGISES~1\apps\qgis\python\plugins\fTools\tools
C:/Users/RCF337/Desktop/test0950

##

**Comment by arx-it** [comment]
Pouvez-vous nous transmettre le projet, la base SQLlite et la couche sur laquelle vous obtenez cette erreur?
